# Generated by Django 4.1.6 on 2023-03-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment',
            field=models.IntegerField(default=None),
        ),
    ]
