# Generated by Django 4.1.6 on 2023-03-23 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappf', '0005_student_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
    ]
